version: '3'
services:
  github-self-runner:
    container_name:  github-self-runner
    build: .
    tty: true
    environment:
      ORG_NAME: 'xxxxxx'
      ACCESS_TOKEN: 'xxxxxxxxx'
      EPHEMERAL: '1'
      JOBS_ACCEPTANCE_TIMEOUT: '120'
      RUNNER_SCOPE: 'org'
#    command: tail -f /dev/null
