name: Check Self Host Runner Status
on:
  workflow_dispatch:
    inputs:
      jobId:
        description: 'Self Hosted Runner Job Id'
        required: true
jobs:
  JobStatus:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check Job Status
        run: |
          echo Self Hosted Runner Job Id: ${{ github.event.inputs.jobId }}
          watch -n 10 -e echo $(aws batch describe-jobs --jobs ${{ github.event.inputs.jobId }} | jq -r '.jobs[0].status')
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
