name: Check Self Host Runner Status
on:
  workflow_dispatch:
    inputs:
      jobId:
        description: 'Self Hosted Runner Job Id'
        required: true
jobs:
  JobStatus:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check Job Status
        run: |
          echo "::notice title=Self Hosted Runner Job Id::${{ github.event.inputs.jobId }}"
          OLD_STATUS=
          while true; do
            STATUS=$(aws --region ap-northeast-1 batch describe-jobs --jobs "${{ github.event.inputs.jobId }}" | jq -r '.jobs[0].status')
            if [[ "${STATUS}" != "${OLD_STATUS}" ]]; then
              echo "::notice title=Status::[$(date +'%Y/%m/%d %T %Z')] $STATUS"
            fi
            OLD_STATUS=$STATUS
            if [[ "${STATUS}" = "FAILED" || "${STATUS}" = "SUCCEEDED" ]]; then
              LOG_NAME=$(aws --region ap-northeast-1 batch describe-jobs --jobs "${{ github.event.inputs.jobId }}" | jq -r '.jobs[0].container.logStreamName')
              aws --region ap-northeast-1 logs get-log-events --log-group-name /aws/batch/job --log-stream-name "${LOG_NAME}"|grep message| rev | cut -c 3- | rev | cut -c 25- 
            fi
            [[ "${STATUS}" = "" ]] && exit 1
            [[ "${STATUS}" = "null" ]] && exit 1
            [[ "${STATUS}" = "FAILED" ]] && exit 1
            [[ "${STATUS}" = "SUCCEEDED" ]] && exit 0
            sleep 10
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
