name: Check Github Runner Version
on:
  #schedule:
  #  - cron: "0 15 * * 0,1,2,3,4"
  workflow_dispatch:
permissions:
  id-token: write # required!
  contents: write
jobs:
  CheckVersion:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Check Github Runner Version
        run: |
          ORG_REPO=https://github.com/myoung34/docker-github-actions-runner
          VER1=$(gh release view --json tagName | jq -r '.tagName' | cut -c 2-)
          echo current: ${VER1}
          echo VER1=${VER1} >> $GITHUB_ENV
          VER2=$(gh release view -R "${ORG_REPO}" --json tagName | jq -r '.tagName')
          echo latest: ${VER2}
          echo VER2=${VER2} >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v1
        if: env.VER1 != env.VER2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Update Self Host Runner
        if: env.VER1 != env.VER2
        run: |
          gh release create v${{ env.VER2 }}
          aws codebuild start-build --project-name eg-test-githubself-hosted-runner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
