name: Check Self Host Runner Status
on:
  workflow_dispatch:
    inputs:
      jobId:
        description: 'Self Hosted Runner Job Id'
        required: true
jobs:
  JobStatus:
    runs-on: ubuntu-latest
    steps:
      - name: Check Job Status
        run: |
          echo "::notice title=Self Hosted Runner Job Id::${{ github.event.inputs.jobId }}"
          aws batch describe-jobs --jobs ${{ github.event.inputs.jobId }}
          echo "::notice title=Status::$STATUS"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
