name: helloAndCheck
on:
  workflow_dispatch:
jobs:
  StartRunner:
    runs-on: ubuntu-latest
    steps:
      - name: Start Self Hosted Runner
        run: |
          JOB_21_ID=$(aws --region ap-northeast-1 batch submit-job \
          --job-name test \
          --job-queue github_self_runner_spot \
          --job-definition github_self_runner \
          --timeout attemptDurationSeconds=180 \
          --container-overrides '{"vcpus": 2, "environment":[{"name":"REPO_URL","value":"https://github.com/${{ github.repository }}/"},{"name":"LABELS","value":"helloAndCheck"}]}' \
          | jq -r '.jobId' )
          echo "JOB_21_ID=$JOB_21_ID" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  JobStatus:
    needs: [StartRunner]
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check Job Status
        run: |
          watch -n 5 -t -e echo $(aws batch describe-jobs --jobs ${{ env.JOB_21_ID }} | jq -r '.jobs[0].status')
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  test:
    needs: [StartRunner]
    runs-on: helloAndCheck
    steps:
      - name: Hello
        run: |
          echo hello
