name: hello
on:
  workflow_dispatch:
jobs:
  StartRunner:
    runs-on: ubuntu-latest
    steps:
      - name: Start Self Hosted Runner
        run: |
          aws --region us-east-1 batch submit-job \
          --job-name test \
          --job-queue github_self_runner_spot \
          --job-definition github_self_runner \
          --timeout attemptDurationSeconds=60 \
          --container-overrides '{"vcpus": 8, "environment":[{"name":"LABELS","value":"loadtest"},{"name":"REPO_URL","value":"https://github.com/${{ github.repository }}/"}]}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  test:
    needs: [StartRunner]
    runs-on: loadtest
    steps:
      - name: Hello
        run: |
          echo hello
