name: test
on:
  workflow_dispatch:
jobs:
  RunnerToken:
    runs-on: ubuntu-latest
    steps:
      - name: Start Self Hosted Runner
        run: |
          curl -sX POST -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/${{ github.repository }}/actions/runners/registration-token
