name: test
on:
  workflow_dispatch:
jobs:
  RunnerToken:
    runs-on: ubuntu-latest
    steps:
      - name: Start Self Hosted Runner
        run: |
          REG_TOKEN=$(gh api --method POST -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runners/registration-token | jq .token --raw-output)
          echo $REG_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}