name: test
on:
  workflow_dispatch:
jobs:
  RunnerToken:
    runs-on: ubuntu-latest
    steps:
      - name: Start Self Hosted Runner
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runners/registration-token
