name: test
on:
  workflow_dispatch:
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  RunnerToken:
    runs-on: ubuntu-latest
    steps:
      - name: Start Self Hosted Runner
        run: |
          REG_TOKEN=$(gh api --method POST -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runners/registration-token | jq .token --raw-output)
          echo $REG_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}